replicaCount: 1

image:
  repository: ghcr.io/redboxing/redbot
  pullPolicy: IfNotPresent
  tag: latest
  imagePullSecrets:
  - name: regcred

bot:
  token: ""

spotify:
  client_id: ""
  client_secret: ""

database:
  dialect: "mariadb"
  host: ""
  port: 3306
  database: "redbot"
  user: "redbot"
  password: ""

author_id: 0