apiVersion: apps/v1
kind: Deployment
metadata:
  name: redbot
  labels:
    app: redbot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redbot
  template:
    metadata:
      labels:
        app: redbot
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          name: "{{ .Chart.Name }}"
          env:
            - name: BOT_TOKEN
              value: "{{ .Values.bot.token }}"
            - name: RSPOTIFY_CLIENT_ID
              value: "{{ .Values.spotify.client_id }}"
            - name: RSPOTIFY_CLIENT_SECRET
              value: "{{ .Values.spotify.client_secret }}"
            - name: DATABASE_DIALECT
              value: "{{ .Values.database.dialect }}"
            - name: DATABASE_HOST
              value: "{{ .Values.database.host }}"
            - name: DATABASE_PORT
              value: "{{ .Values.database.port }}"
            - name: DATABASE_NAME
              value: "{{ .Values.database.database }}"
            - name: DATABASE_USER
              value: "{{ .Values.database.user }}"
            - name: DATABASE_PASSWORD
              value: "{{ .Values.database.password }}"
            - name: AUTHOR_ID
              value: "{{ .Values.author_id }}"
